"""Scoring snapshot + focused unit tests.

The snapshot test pins the AI Value formula against a small set of
representative models. Any change to the formula or its inputs (TTFT
floor, latency knees, workload alphas, fallback quality scale, …) will
fail this test — at which point either the change is wrong, or the
snapshot in EXPECTED needs to be regenerated and the diff reviewed.

The focused tests exercise the smaller helpers (open-weight rules,
fallback quality scale, Arena match, latency penalty symmetry) so a
regression there fails with a specific message instead of a giant
snapshot diff.
"""

import math

import pytest

from app.scoring import (
    compute_model_score,
    is_open_weight,
    latency_penalty,
    quality_index_0_100,
    LATENCY_KNEE,
)
from app.scraper import _match_arena_elo, ARENA_NAMES


# ── Sample models: pick a deliberate spread ──────────────────────────────────
# - openai-gpt-4o: US region, no aa_tps → class-prior throughput
# - mistral-medium: EU region, has aa_tps → measured throughput
# - aleph-pharia: no aa_index → fallback quality scale exercised
# - openai-emb: embeddings → output_usd=0, tps=0 branches

SAMPLE_MODELS = [
    {
        "id": "openai-gpt-4o",
        "provider": "OpenAI", "model": "GPT-4o", "model_id": "gpt-4o",
        "categories": ["chat", "vision", "code", "reasoning"],
        "input_usd_per_1m": 2.50, "output_usd_per_1m": 10.00, "context_window_k": 128,
        "primary_region": "us-east-1", "has_eu_endpoint": False, "eu_latency_ms": 175,
        "quality_score": 9.0, "aa_index": 25.0,
    },
    {
        "id": "mistral-medium",
        "provider": "Mistral AI", "model": "Mistral Medium 3", "model_id": "mistral-medium-latest",
        "categories": ["chat", "code"],
        "input_usd_per_1m": 2.70, "output_usd_per_1m": 8.10, "context_window_k": 128,
        "primary_region": "eu-west", "has_eu_endpoint": True, "eu_latency_ms": 65,
        "quality_score": 8.5, "aa_index": 38.0, "aa_tps": 150,
    },
    {
        "id": "aleph-pharia",
        "provider": "Aleph Alpha", "model": "Pharia-1-LLM", "model_id": "pharia-1-llm-7b",
        "categories": ["chat"],
        "input_usd_per_1m": 1.20, "output_usd_per_1m": 3.60, "context_window_k": 8,
        "primary_region": "eu-central", "has_eu_endpoint": True, "eu_latency_ms": 40,
        "quality_score": 7.0,
    },
    {
        "id": "openai-emb",
        "provider": "OpenAI", "model": "text-embedding-3-small", "model_id": "text-embedding-3-small",
        "categories": ["embeddings"],
        "input_usd_per_1m": 0.02, "output_usd_per_1m": 0.0, "context_window_k": 8,
        "primary_region": "us-east-1", "has_eu_endpoint": False, "eu_latency_ms": 175,
        "quality_score": 7.5, "aa_index": 0,
    },
]

CASES = [
    ("chat",      "interactive", "vilnius"),
    ("rag",       "batch",       "frankfurt"),
    ("code",      "interactive", "nyc"),
    ("summarize", "insensitive", "tokyo"),
]

# Generated by running compute_model_score against SAMPLE_MODELS with the
# measured-RTT fixture disabled (haversine only). Regenerate with the
# script in this file's docstring when the formula intentionally changes.
EXPECTED = {
    "chat|interactive|vilnius": [
        {"id": "openai-gpt-4o",   "ai_value_score": -0.618, "intel_per_dollar": 3.08,    "blended_cost_usd_per_1m": 8.125,  "quality_index": 25.0, "effective_latency_ms": 175, "output_tokens_per_sec": 55,  "throughput_source": "class-prior", "latency_penalty": 1.106},
        {"id": "mistral-medium",  "ai_value_score":  0.068, "intel_per_dollar": 5.63,    "blended_cost_usd_per_1m": 6.75,   "quality_index": 38.0, "effective_latency_ms":  65, "output_tokens_per_sec": 150, "throughput_source": "aa-measured", "latency_penalty": 0.682},
        {"id": "aleph-pharia",    "ai_value_score":  0.194, "intel_per_dollar": 9.0,     "blended_cost_usd_per_1m": 3.0,    "quality_index": 27.0, "effective_latency_ms":  43, "output_tokens_per_sec": 120, "throughput_source": "class-prior", "latency_penalty": 0.761},
        {"id": "openai-emb",      "ai_value_score":  3.143, "intel_per_dollar": 1575.0,  "blended_cost_usd_per_1m": 0.02,   "quality_index": 31.5, "effective_latency_ms": 175, "output_tokens_per_sec": 0,   "throughput_source": "n/a",         "latency_penalty": 0.054},
    ],
    "rag|batch|frankfurt": [
        {"id": "openai-gpt-4o",   "ai_value_score":  0.947, "intel_per_dollar": 6.67,    "blended_cost_usd_per_1m": 3.75,   "quality_index": 25.0, "effective_latency_ms": 164, "output_tokens_per_sec": 55,  "throughput_source": "class-prior", "latency_penalty": -0.123},
        {"id": "mistral-medium",  "ai_value_score":  1.436, "intel_per_dollar": 10.56,   "blended_cost_usd_per_1m": 3.6,    "quality_index": 38.0, "effective_latency_ms":  50, "output_tokens_per_sec": 150, "throughput_source": "aa-measured", "latency_penalty": -0.412},
        {"id": "aleph-pharia",    "ai_value_score":  1.656, "intel_per_dollar": 16.88,   "blended_cost_usd_per_1m": 1.6,    "quality_index": 27.0, "effective_latency_ms":  25, "output_tokens_per_sec": 120, "throughput_source": "class-prior", "latency_penalty": -0.429},
        {"id": "openai-emb",      "ai_value_score":  3.532, "intel_per_dollar": 1575.0,  "blended_cost_usd_per_1m": 0.02,   "quality_index": 31.5, "effective_latency_ms": 164, "output_tokens_per_sec": 0,   "throughput_source": "n/a",         "latency_penalty": -0.335},
    ],
    "code|interactive|nyc": [
        {"id": "openai-gpt-4o",   "ai_value_score": -1.139, "intel_per_dollar": 2.86,    "blended_cost_usd_per_1m": 8.75,   "quality_index": 25.0, "effective_latency_ms":  71, "output_tokens_per_sec": 55,  "throughput_source": "class-prior", "latency_penalty": 1.595},
        {"id": "mistral-medium",  "ai_value_score": -0.454, "intel_per_dollar": 5.28,    "blended_cost_usd_per_1m": 7.2,    "quality_index": 38.0, "effective_latency_ms": 111, "output_tokens_per_sec": 150, "throughput_source": "aa-measured", "latency_penalty": 1.176},
        {"id": "aleph-pharia",    "ai_value_score": -0.344, "intel_per_dollar": 8.44,    "blended_cost_usd_per_1m": 3.2,    "quality_index": 27.0, "effective_latency_ms": 118, "output_tokens_per_sec": 120, "throughput_source": "class-prior", "latency_penalty": 1.27},
        {"id": "openai-emb",      "ai_value_score":  3.435, "intel_per_dollar": 1575.0,  "blended_cost_usd_per_1m": 0.02,   "quality_index": 31.5, "effective_latency_ms":  71, "output_tokens_per_sec": 0,   "throughput_source": "n/a",         "latency_penalty": -0.238},
    ],
    "summarize|insensitive|tokyo": [
        {"id": "openai-gpt-4o",   "ai_value_score":  1.292, "intel_per_dollar": 7.86,    "blended_cost_usd_per_1m": 3.1818, "quality_index": 25.0, "effective_latency_ms": 229, "output_tokens_per_sec": 55,  "throughput_source": "class-prior", "latency_penalty": -0.397},
        {"id": "mistral-medium",  "ai_value_score":  1.583, "intel_per_dollar": 11.91,   "blended_cost_usd_per_1m": 3.1909, "quality_index": 38.0, "effective_latency_ms": 178, "output_tokens_per_sec": 150, "throughput_source": "aa-measured", "latency_penalty": -0.507},
        {"id": "aleph-pharia",    "ai_value_score":  1.78,  "intel_per_dollar": 19.04,   "blended_cost_usd_per_1m": 1.4182, "quality_index": 27.0, "effective_latency_ms": 165, "output_tokens_per_sec": 120, "throughput_source": "class-prior", "latency_penalty": -0.5},
        {"id": "openai-emb",      "ai_value_score":  3.732, "intel_per_dollar": 1575.0,  "blended_cost_usd_per_1m": 0.02,   "quality_index": 31.5, "effective_latency_ms": 229, "output_tokens_per_sec": 0,   "throughput_source": "n/a",         "latency_penalty": -0.535},
    ],
}

SNAPSHOT_FIELDS = (
    "ai_value_score",
    "intel_per_dollar",
    "blended_cost_usd_per_1m",
    "quality_index",
    "effective_latency_ms",
    "output_tokens_per_sec",
    "throughput_source",
    "latency_penalty",
)


@pytest.mark.parametrize("workload,sensitivity,city", CASES)
def test_scoring_snapshot(workload, sensitivity, city):
    key = f"{workload}|{sensitivity}|{city}"
    expected_rows = EXPECTED[key]
    for sample, expected in zip(SAMPLE_MODELS, expected_rows):
        actual = compute_model_score(dict(sample), workload, sensitivity, city)
        assert sample["id"] == expected["id"]
        for field in SNAPSHOT_FIELDS:
            actual_v = actual[field]
            expected_v = expected[field]
            if isinstance(expected_v, float):
                assert actual_v == pytest.approx(expected_v, abs=0.01), (
                    f"{key} / {sample['id']} / {field}: {actual_v} != {expected_v}"
                )
            else:
                assert actual_v == expected_v, (
                    f"{key} / {sample['id']} / {field}: {actual_v!r} != {expected_v!r}"
                )


# ── Focused tests for the smaller helpers ────────────────────────────────────

class TestQualityFallback:
    """quality_index_0_100 must keep fallback strictly below AA frontier."""

    def test_uses_aa_index_when_present(self):
        assert quality_index_0_100({"aa_index": 42.0}) == 42.0

    def test_fallback_caps_below_frontier(self):
        # Even an extreme seeded quality_score must not exceed the cap.
        assert quality_index_0_100({"quality_score": 10.0}) <= 55.0

    def test_fallback_floor_is_zero(self):
        # Negative / tiny scores clamp to 0, not negative.
        assert quality_index_0_100({"quality_score": 1.0}) == 0.0

    def test_old_bug_no_longer_dominates(self):
        # The pre-fix fallback returned 98 for q=9.8 and would outrank AA frontier (~57).
        fallback = quality_index_0_100({"quality_score": 9.8})
        frontier = quality_index_0_100({"aa_index": 57.0})
        assert fallback < frontier


class TestOpenWeightClassification:
    @pytest.mark.parametrize("provider,model_id,expected", [
        ("OpenAI",       "gpt-4o",                 False),
        ("Anthropic",    "claude-opus-4-7",        False),
        ("Meta (API)",   "llama-3.3-70b",          True),
        ("DeepSeek",     "deepseek-chat",          True),
        ("Mistral AI",   "mistral-large-latest",   False),   # proprietary subset
        ("Mistral AI",   "open-mistral-7b",        True),
        ("Mistral AI",   "codestral-latest",       False),
        ("Google",       "gemma-2-9b",             True),
        ("Google",       "gemini-2.5-pro",         False),
        ("Aleph Alpha",  "pharia-1-llm-7b",        True),
        ("Aleph Alpha",  "luminous-supreme",       False),
        ("OpenRouter",   "deepseek/deepseek-r1",   True),
        ("OpenRouter",   "openai/gpt-5",           False),
    ])
    def test_known_pairs(self, provider, model_id, expected):
        assert is_open_weight({"provider": provider, "model_id": model_id}) is expected


class TestLatencyPenalty:
    """Penalty must be symmetric log around the knee."""

    def test_zero_at_knee(self):
        for sensitivity, knee in LATENCY_KNEE.items():
            assert latency_penalty(knee, sensitivity) == pytest.approx(0.0, abs=1e-9)

    def test_bonus_below_knee(self):
        # Sub-knee latency earns a negative (bonus) score.
        assert latency_penalty(10, "interactive") < 0
        # And the bonus is bounded — even latency_ms=0 stays above -1.
        assert latency_penalty(0, "interactive") > -1.0

    def test_penalty_above_knee(self):
        assert latency_penalty(2000, "interactive") > 1.0

    def test_one_decade_above_knee_is_about_one(self):
        # At 10× knee, the penalty should be close to +1 (log10 of ~10).
        ten_x = 10 * LATENCY_KNEE["interactive"]
        # The (knee/4) shift makes this slightly less than 1; allow a band.
        assert 0.7 < latency_penalty(ten_x, "interactive") < 1.0


class TestArenaMatch:
    def test_explicit_map_wins(self):
        arena = {"gpt-4o-2024-08-06": 1305.0}
        m = {"id": "openai-gpt-4o", "model": "GPT-4o"}
        assert _match_arena_elo(m, arena) == 1305.0

    def test_no_substring_collision(self):
        # The old bug: 'gpt-4' substring would match 'gpt-4o' for the gpt-4.1 model.
        arena = {
            "gpt-4o-2024-08-06":     1305.0,
            "gpt-4.1-2025-04-14":    1413.0,
        }
        m41 = {"id": "openai-gpt-4-1", "model": "GPT-4.1"}
        assert _match_arena_elo(m41, arena) == 1413.0  # not 1305

    def test_unmapped_returns_none(self):
        arena = {"gpt-4o-2024-08-06": 1305.0}
        m = {"id": "totally-new-model", "model": "Totally New"}
        assert _match_arena_elo(m, arena) is None

    def test_arena_names_keys_are_strings(self):
        # Catch typos in the explicit map at test time.
        for key, val in ARENA_NAMES.items():
            assert isinstance(key, str) and key
            assert isinstance(val, str) and val
